from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(10, 20, 151, 41))
        self.add_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.add_button.setObjectName("add_button")
        self.look_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.look_up_button.setGeometry(QtCore.QRect(170, 20, 151, 41))
        self.look_up_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.look_up_button.setObjectName("look_up_button")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(330, 20, 141, 41))
        self.update_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.update_button.setObjectName("update_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(480, 20, 141, 41))
        self.delete_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.delete_button.setObjectName("delete_button")
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(630, 20, 141, 41))
        self.quit_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.quit_button.setObjectName("quit_button")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 80, 261, 211))
        self.widget.setObjectName("widget")
        self.department_input = QtWidgets.QLineEdit(self.widget)
        self.department_input.setGeometry(QtCore.QRect(110, 90, 131, 21))
        self.department_input.setObjectName("department_input")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 51, 21))
        self.label_3.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_4.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_4.setObjectName("label_4")
        self.confirm_button = QtWidgets.QPushButton(self.widget)
        self.confirm_button.setGeometry(QtCore.QRect(20, 180, 121, 31))
        self.confirm_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.confirm_button.setObjectName("confirm_button")
        self.name_input = QtWidgets.QLineEdit(self.widget)
        self.name_input.setGeometry(QtCore.QRect(110, 50, 131, 21))
        self.name_input.setObjectName("name_input")
        self.id_input = QtWidgets.QLineEdit(self.widget)
        self.id_input.setGeometry(QtCore.QRect(110, 10, 131, 21))
        self.id_input.setObjectName("id_input")
        self.title_input = QtWidgets.QLineEdit(self.widget)
        self.title_input.setGeometry(QtCore.QRect(110, 130, 131, 21))
        self.title_input.setObjectName("title_input")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 21, 21))
        self.label_2.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 31, 21))
        self.label_5.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.confirm_button_2 = QtWidgets.QPushButton(self.widget)
        self.confirm_button_2.setGeometry(QtCore.QRect(50, 50, 111, 31))
        self.confirm_button_2.setStyleSheet("font: 10pt \"Verdana\";")
        self.confirm_button_2.setObjectName("confirm_button_2")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(140, 180, 20, 31))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.clear_button = QtWidgets.QPushButton(self.widget)
        self.clear_button.setGeometry(QtCore.QRect(160, 180, 81, 31))
        self.clear_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.clear_button.setObjectName("clear_button")
        self.purge_button = QtWidgets.QPushButton(self.centralwidget)
        self.purge_button.setGeometry(QtCore.QRect(610, 300, 161, 31))
        self.purge_button.setStyleSheet("font: 10pt \"Verdana\";")
        self.purge_button.setObjectName("purge_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.id_input.returnPressed.connect(self.confirm_button.animateClick)
        self.name_input.returnPressed.connect(self.confirm_button.animateClick)
        self.department_input.returnPressed.connect(self.confirm_button.animateClick)
        self.title_input.returnPressed.connect(self.confirm_button.animateClick)
        self.add_button.clicked.connect(self.add_button.setFocus)
        self.confirm_button.clicked.connect(self.widget.update)
        self.confirm_button.clicked.connect(self.id_input.update)
        self.confirm_button_2.clicked.connect(self.widget.update)
        self.confirm_button_2.clicked.connect(self.id_input.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.add_button, self.look_up_button)
        MainWindow.setTabOrder(self.look_up_button, self.update_button)
        MainWindow.setTabOrder(self.update_button, self.delete_button)
        MainWindow.setTabOrder(self.delete_button, self.quit_button)
        MainWindow.setTabOrder(self.quit_button, self.id_input)
        MainWindow.setTabOrder(self.id_input, self.name_input)
        MainWindow.setTabOrder(self.name_input, self.department_input)
        MainWindow.setTabOrder(self.department_input, self.title_input)
        MainWindow.setTabOrder(self.title_input, self.confirm_button)
        MainWindow.setTabOrder(self.confirm_button, self.confirm_button_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_button.setText(_translate("MainWindow", "Add new employee"))
        self.look_up_button.setText(_translate("MainWindow", "Look Up Employee"))
        self.update_button.setText(_translate("MainWindow", "Update Employee"))
        self.delete_button.setText(_translate("MainWindow", "Delete Employee"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Department"))
        self.confirm_button.setText(_translate("MainWindow", "Add employee"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "Title"))
        self.confirm_button_2.setText(_translate("MainWindow", "Look up"))
        self.clear_button.setText(_translate("MainWindow", "Clear All"))
        self.purge_button.setText(_translate("MainWindow", "Purge all employees"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
